Home work 17
Fullstack-Alfanar/reema-r-homeWorks pull request #1
Opened 2022-04-06 10:07 UTC by reemaRahhal

I have been finished my task ,  I searched in  google for valid email pattern then I wrote a function and did a lot of testing.
please, can you reviwe my task

2022-04-12 22:29 UTC, EliasSalom requested changes
please check my comments and fix the issues!!

2022-04-12 22:29 UTC, EliasSalom commented on Home_Work_17/js/script.js
> + function validEmail() {
this function has been used before and copied before please change it to a new one

2022-04-16 15:21 UTC, reemaRahhal commented on Home_Work_17/js/script.js
> + function validEmail() {
I had changed the function.

2022-04-16 21:50 UTC, EliasSalom approved these changes
Good work

2022-04-16 21:50 UTC, merged