Hw 18
Fullstack-Alfanar/reema-r-homeWorks pull request #2
Opened 2022-04-10 10:28 UTC by reemaRahhal

Hi Elias , 
I have done the home work , in my task I built an algorithm that receives an personal details from the user, as required in the lesson (name,age,id,email)  and send them to another functions accordingly. Foe example the algorithm recevies the value of id number which the user has entered  then, the algorithem send the value to function that check if the ID is Valid or Not. 
And I did a documentation for almost each line of code.
At the end I enjoyed doing the task, especially at the stage of building a function of ID integrity.
please review my task

2022-04-12 22:04 UTC, EliasSalom requested changes
please read my comment and fix the issue!!

2022-04-12 22:04 UTC, EliasSalom commented on Home_Work_17/js/script.js
> + function validEmail() {
this function has been copied from a website please change it and write a new one !!!

2022-04-16 22:13 UTC, reemaRahhal commented on Home_Work_17/js/script.js
> + function validEmail() {
I had fixed the function .

2022-04-16 22:15 UTC, EliasSalom approved these changes
Good Work

2022-04-16 22:15 UTC, merged