Hw 19
Fullstack-Alfanar/reema-r-homeWorks pull request #3
Opened 2022-04-13 14:16 UTC by reemaRahhal

Hi Elias  , 
I finished my task. In the task I built an algorithm that receives data from the user checks if the data is valid then adds the data to the table. In addition, the page shows to the user a card of the number of students and another card shows the average of students if the average is lower than 80 it will be painted red. If the average is equal or greater than  80 the average will be green. 
Furthermore, I made a design for the page and a documentation for  lines of code in JS file. 
please reviwe my task

2022-04-13 14:56 UTC, EliasSalom reviewed
I'm working on it

2022-04-16 22:24 UTC, reemaRahhal commented
I would like to receive comments about my task please.

2022-04-16 22:26 UTC, EliasSalom requested changes
i think you missing an important part that I asked for `local storage`

2022-04-16 22:26 UTC, EliasSalom commented on Home_Work_19/js/script.js
> +     if(!/^[a-zA-Z]+$/.test(fname.value)  ) {
what about the name with one letter ???

2022-04-16 22:31 UTC, reemaRahhal commented on Home_Work_19/js/script.js
> +     if(!/^[a-zA-Z]+$/.test(fname.value)  ) {
This task for lesson 19  and it includes a function that chek if the length of the name less than 2 letter, the user recieve a message

2022-04-16 22:35 UTC, EliasSalom commented on Home_Work_19/js/script.js
> +     if(!/^[a-zA-Z]+$/.test(fname.value)  ) {
oh okay because I asked to use the same project just to add this future, but if you create a new one with `local storage` that's amazing

2022-04-18 20:51 UTC, reemaRahhal commented on Home_Work_19/js/script.js
> +     if(!/^[a-zA-Z]+$/.test(fname.value)  ) {
Hi Elias,
can you merge branch HW-19 to main , please

2022-04-19 14:14 UTC, merged