Hw 22
Fullstack-Alfanar/reema-r-homeWorks pull request #6
Opened 2022-05-01 13:58 UTC by reemaRahhal

Hi Elias, 
I finished my task regarding question password validition,
I used in ascii charecter code to check if the characters that user entered are in the range accordingly. 
Regarding the question of sorting numbers's array , in academic studies, I studied several types of sorting and 
used one of them is called counting sorting which time's complecation is  O(n). 
can you review my task please .

2022-05-05 00:10 UTC, EliasSalom requested changes
please check my comment and change it

2022-05-05 00:10 UTC, EliasSalom commented on Home_Work_22/js/sort.js
> +      counter[i]--;
in this loop, there is a `while` inside `for` so this will make the function be `O(n^2)`

2022-05-09 10:08 UTC, reemaRahhal commented on Home_Work_22/js/sort.js
> +      counter[i]--;
Hi Elias, 
I changed the sorting  array  function, please review my task

2022-05-18 19:09 UTC, EliasSalom approved these changes
have you solved this task alone?

2022-05-18 21:23 UTC, merged